#log:
#  level: DEBUG

api:
  dashboard: true

providers:
  docker:
    exposedbydefault: false
    endpoint: unix:///var/run/docker.sock
    network: web

entrypoints:
  http:
    address: :80
  https:
    address: :443

certificatesResolvers:
  sample:
    acme:
      tlschallenge: {}
      email: you-email@gmail.com
      storage: acme.json